
using Microsoft.VisualBasic.FileIO;
using ProtoBuf;
using SteamKit2.GC.Deadlock.Internal;
using System.IO;
using System.Reflection.Metadata;
using System.Security.Cryptography;
using System.Text.RegularExpressions;
using ValveKeyValue;
using ValveResourceFormat;
using ValveResourceFormat.ResourceTypes;
using ValveResourceFormat.Serialization.KeyValues;
using KVObject = ValveResourceFormat.Serialization.KeyValues.KVObject;
using KVValue = ValveResourceFormat.Serialization.KeyValues.KVValue;

namespace ProtobufDecodeTestDeadlock
{
	internal class Program
	{
		static void Main(string[] args)
		{
			//It's possible to call fetchBuildsByPath(string path) with a custom filepath
			//string kv3Path = "D:\\Steam\\userdata\\1674155511\\1422450\\remote\\cfg\\cached_hero_builds.kv3";
			/*
			 * .fetchBuilds(string username) retrieves Steam ID of a local Steam User automatically by it's public Username.(I could easily make it the account name but honestly who cares)
			 * Probably extremely unstable since I had to write my own little parser for it.(long past midnight too, I just couldn't stop until I got it working)
			 * Fetches the existing builds from the cached_hero_builds.kv3 file into memory.
			 */
			HeroBuildsManager.fetchBuilds("SolTom");
			const string buildName = "Build Generated by SolTom";

			CMsgHeroBuild workBuild = new CMsgHeroBuild();
			workBuild.name = buildName;
			workBuild.last_updated_timestamp = HeroBuildsManager.unixTimeNow();
			//Takes the retrieved Steam User ID, because it's saved internally in the static class after
			//the fetch if the fetch was done using the fetchBuilds(string username) variant rather than fetchBuildsByPath(string path) one.
			//Otherwise input the correct number yourself.
			workBuild.author_account_id = HeroBuildsManager.currentSteamUserId;
			//Generates hero build id that isn't already taken.
			workBuild.hero_build_id = HeroBuildsManager.getNewBuildID();
			//Set current build of given hero to the one with id in the 2nd argument
			HeroBuildsManager.setHeroBuildId("Victor", workBuild.hero_build_id);
			//case sensitive, you can always check the heroes.csv to be sure tho, custom aliases are possible
			//Both a List and getHero work.
			//workBuild.hero_id = HeroBuildsManager.heroes.Single(x=>x.commonName == "Victor").internalId;
			workBuild.hero_id = HeroBuildsManager.getHero("Victor").internalId;

			workBuild.details = new();
			//regular category example
			//CMsgHeroBuild.BuildModCategory buildModCategory = new();
			//buildModCategory.height = 500;
			//buildModCategory.width = 600;
			//buildModCategory.name = "Random Category";
			//buildModCategory.optional = false;
			
			CMsgHeroBuild.BuildModEntry buildModEntry = new CMsgHeroBuild.BuildModEntry();
			//Many ways to do the same thing
			//Preferably you'd go getItem but if you need to do some filtering then the List is still there and public
			//buildModEntry.ability_id = HeroBuildsManager.items.Single(x=>x.name == "Trophy Collector").id;
			//There is also a shoppableItems List
			//buildModEntry.ability_id = HeroBuildsManager.shoppableItems.Single(x=>x.name == "Trophy Collector").id;
			//The simplest way
			//buildModEntry.ability_id = HeroBuildsManager.getItem("Trophy Collector").id;
			//Make a list of items of one type by name 
			//var viableItems = HeroBuildsManager.items.Where(x => x.item_slot_type == HeroBuildsManager.itemTypes[Models.itemTypesEnum.Vitality]).ToList();
			
			Random random = new Random();
			//example randomizer
			for(int a=0; a<HeroBuildsManager.shoppableItemCosts.Count; a++)
			{
				CMsgHeroBuild.BuildModCategory buildModCategory = new();
				buildModCategory.height = 180;
				buildModCategory.width = 900;
				buildModCategory.name = "Random Category " + HeroBuildsManager.shoppableItemCosts[a].ToString();
				buildModCategory.optional = false;
				for (int b=0; b<HeroBuildsManager.itemTypesList.Count; b++)
				{
					var tempList = HeroBuildsManager.shoppableItems.Where
					(
						x => x.cost == HeroBuildsManager.shoppableItemCosts[a] &&
							x.item_slot_type == HeroBuildsManager.itemTypesList[b]
					)
					.ToList();
					//3 of each category in each price tag
					List<uint> usedIds = new();
					for (int c=0; c<3; c++)
					{
						buildModEntry = new CMsgHeroBuild.BuildModEntry();
						
						buildModEntry.ability_id = tempList[random.Next(tempList.Count)].id;
						if(usedIds.Contains(buildModEntry.ability_id))
						{
							c--;
							continue;
						}
						else
						{
							usedIds.Add(buildModEntry.ability_id);
						}
						buildModCategory.mods.Add(buildModEntry);
					}
				}
				workBuild.details.mod_categories.Add(buildModCategory);
			}

			//There are three types of builds, but you should *probably* always go for the Unpublished type
			HeroBuildsManager.addBuild(workBuild, HeroBuildsManager.buildTypes.Unpublished);
			//Saves all the builds that are in the build Lists inside the manager class.
			//Those Lists are public in case you wanted to analyse or remove those builds for any reason.
			HeroBuildsManager.saveBuilds();
		}
	}
}
